name: CI/CD

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure CMake
        run: cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build _build

      - name: Install
        run: cmake --build _build --target install DESTDIR=_install
